language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build

notifications:
  email: false
  slack: simplauto-projet4:foNTuvnQQK9jRkASWg6Y4Htz
deploy:
  provider: heroku
  app: simplauto-frontend
  api_key:
    secure: 880030fd-f70f-4b67-a928-8ad1fd01ad4d
  on: develop
